### ISSUE TITLE
UVa Visual History Large Image Wrapper Citation

### ISSUE THREAD

**Issue by JocelynTriplett** [uvalib/tracksys#146]
Not terribly urgent, but something Regina and I noticed today.

A patron requested this image: http://fedoraproxy.lib.virginia.edu/fedora/objects/uva-lib:2153911/methods/djatoka:StaticSDef/getStaticImage

If you look at the wrapper, it has a generic citation: U.Va. prints and photographs file, Accession #RG-30/1/10.011, Prints0000 (note specific number), Special Collections, University of Virginia Library, Charlottesville, Va. which is taken from the record here: http://search.lib.virginia.edu/catalog/u3795347

So the patron requested Prints0000. 

Would it be possible to have the citation for Visual History items include each image’s actual prints number?

Here’s the link to the Virgo record, where you can see it is prints00020: http://search.lib.virginia.edu/catalog/uva-lib:2153911

**Comment by mikedurbin** [comment]
The citation format has changed significantly since this ticket was reported.  While I'm not sure it's ideal (in fact, I'm sure it isn't ideal), it doesn't have the same problem reported here.

The current link to the "rights wrapper" for that content is as follows:
http://rightswrapper2.lib.virginia.edu:8090/rights-wrapper/?pid=uva-lib:2153911&pagePid=uva-lib:2153911

I'm closing this ticket, but there's a Jira ticket to address the evolving needs here:
https://jira.lib.virginia.edu/browse/DCMD-279
